const resumeData = {
    header: {
      name: "Ibukunoluwa Joel Adeyoju",
      phone: "+233 50 885 5102",
      email: "adeyojuibukunoluwa1@gmail.com",
      location: "Accra, Greater Accra",
    },
    summary:
      "As a software developer, I have gained extensive experience in programming, application development, and teaching. In my role as the MUITSA academic head, I taught subjects like data structures, algorithms, Python, and C++, creating personalized lesson plans and study guides to support students' learning. During my final-year project, I showcased my skills in user experience design and web development, handling data analysis, wireframe designs, and developing user interfaces using modern technologies. Additionally, I have contributed to software development by testing programs, writing high-quality code, and collaborating with teams to create new applications. With a strong technical skill set and a dedication to delivering quality solutions, I am excited to contribute to future software projects and drive innovation.",
    experience: [
      {
        title: "Media Team Director",
        company: "Glorious RCCG Church",
        location: "Dansoman, Greater Accra",
        date: "06/2021 - Present",
        description: [
          "Led and managed the media team responsible for live-streaming and controlling media during Sunday services and weekly gatherings, ensuring smooth and high-quality audiovisual experiences for attendees and online viewers.",
          "Directed the production and coordination of weekly announcement videos, working closely with the announcement team to capture and deliver engaging content that effectively communicated important updates and events to the church community.",
          "Developed and implemented efficient media workflows and standard operating procedures, optimizing technical setups, equipment usage, and team coordination, resulting in improved efficiency and seamless media operations.",
          "Collaborated with the church leadership and creative teams to conceptualize and execute multimedia projects, including sermon series graphics, promotional videos, and special event productions, enhancing the overall visual communication and branding of the church.",
          "Trained and mentored media team members, providing guidance on technical skills, equipment operation, and creative execution, fostering a collaborative and growth-oriented environment within the team.",
          "Managed media equipment inventory, maintenance, and upgrades, ensuring the availability of up-to-date technology and maintaining a professional media production environment.",
        ],
      },
      {
        title: "Peer Tutor",
        company: "MUITSA (Methodist University Information Technology Student Association)",
        location: "Dansoman, Greater Accra",
        date: "09/2022 - 06/2023",
        description: [
          "For the academic year 2022/2023, I was the MUITSA academic head.",
          "Taught and assisted students in such areas as data structure and algorithms, Python programming, and C++ programming, creating tailored lesson plans and study guides on subject matter.",
          "Supported students with helpful study habits and exam strategies.",
          "Promoted the development of good programming habits and learning skills.",
          "Collaborated with students to complete projects and homework assignments, identify lagging skills, and correct bugs.",
        ],
      },
      {
        title: "Project Manager/Developer",
        company: "Final Year Project (Blockchain Based Land Registration System)",
        location: "Dansoman, Greater Accra",
        date: "09/2022 - 06/2023",
        description: [
          "Methodist University Final Year Project",
          "Created the user experience that fetched, parsed, and formatted analytic data.",
          "Created and oversaw wireframe designs based on client requests.",
          "Developed user interfaces with modern JavaScript frameworks, Python, JavaScript, HTML 5, CSS 3, SCSS, React Native, Solidity, and Django.",
          "Met 100% of deadlines and project goals, and as a result, received promotion upon the successful completion of the project.",
        ],
      },
    ],
    skills: [
      "Front-End Development",
      "React Native",
      "UX and UI Design",
      "Node.js",
      "React",
      "TailwindCss",
      "Python Programming",
      "Data Structure and Algorithm",
      "HTML",
      "CSS",
      "JavaScript (Web Development)",
      "MySql",
      "Graphic Design",
      "GraphQL",
      "3D Object Modeling (Cinema 4D)",
      "Mongoose",
      "Java Programming",
      "Object-Oriented Programming",
      "Django App Development",
      "Problem Resolution",
      "Photo Editing (Photoshop)",
    ],
    education: [
      {
        institution: "Methodist University Ghana",
        location: "Dansoman, Greater Accra",
        date: "06/2023",
        details: [
          "Member of the MUITSA (Methodist University Information Technology Student Association) - actively participated in association meetings, events, and workshops.",
          "Academic Head of MUITSA: responsible for organizing academic activities, coordinating study sessions, and providing support to fellow students.",
          "Tutors for data structure and algorithms, Python programming, and C++ programming - assisted students with understanding and practicing these subjects.",
          "Participant in hackathons and coding competitions - engaged in team-based problem-solving and showcased programming skills.",
          "Workshop attendee - participated in technology workshops and seminars to enhance knowledge and stay updated with the latest trends in the IT industry.",
          "Volunteer for IT-related events - offered support and assistance during IT conferences, seminars, and campus IT initiatives.",
          "Project team member - collaborated with classmates on various IT projects, working together to develop innovative solutions.",
          "Attendee of guest lectures and industry talks - gained insights from industry professionals and experts in the field of IT.",
          "Contributor to open-source projects - actively participated in open-source communities and contributed to the development of software applications.",
          "Participant in IT networking events - engaged with professionals in the IT field, expanding professional connections and exploring potential career opportunities.",
        ],
      },
    ],
    certificates: [
      "Data Science Methodology-IBM, Cognitive class.ai",
      "Introduction to Data Science-IBM, Cognitive class.ai",
      "Data Science Tools-IBM, Cognitive class.ai",
      "Data Analysis with Python-IBM, Cognitive class.ai",
      "Python 101 for Data Science-IBM, Cognitive class.ai",
      "Data Visualization with Python-IBM, Cognitive class.ai",
      "Digital Skills Bootcamp '21, Springboard-Ghana cares youth dialogues(Oct, 2021)",
    ],
    projects: [
      {
        title: "Snake Game with Java Object Programming",
        description: "Classic Snake game developed using Java's Object-Oriented Programming principles.",
        link: "/snake-game",
      },
      {
        title: "E-commerce website with HTML, CSS, and JavaScript",
        description: "An e-commerce website prototype created using HTML, CSS, and JavaScript.",
        link: "/e-commerce-website",
      },
      {
        title: "Face recognition program with Python (OpenCV library)",
        description: "A Python program that uses the OpenCV library for face recognition.",
        link: "/face-recognition",
      },
      {
        title: "Online salon booking with a multi-salon application",
        description: "Web application for salon booking with support for multiple salons.",
        link: "/salon-booking",
      },
      {
        title: "E-commerce system (React)-MERN stack development",
        description: "Full-stack e-commerce system developed using the MERN (MongoDB, Express, React, Node.js) stack.",
        link: "/e-commerce-system",
      },
      {
        title: "Blockchain-based land registration system using React Vite, Tailwind CSS, and Solidity.",
        description: "A blockchain-based land registration system developed with React Vite, Tailwind CSS, and Solidity.",
        link: "/blockchain-land-registration",
      },
      {
        title: "Lead Generating Extension for Chrome Browser (JavaScript, HTML5, CSS).",
        description: "A Chrome browser extension for lead generation developed with JavaScript, HTML5, and CSS.",
        link: "/chrome-extension",
      },
      {
        title: "Movie Search Engine With Integrating API (React Framework).",
        description: "A movie search engine web app developed using the React framework.",
        link: "/movie-search-engine",
      },
    ],
    socialMedia: {
      linkedIn: "https://www.linkedin.com/in/adeyoju-ibukunoluwa-375018209/",
      github: "https://github.com/Joeteck",
      twitter: "https://twitter.com/AdeyojuIbukuno1",
    },
  };
  
  export default resumeData;  